from django.db import models


class Album(models.Model):
	#album_id autogenerated
	albumName = models.CharField(max_length=25)
	albumCreatedTime = models.DateTimeField
	albumModifiedTIme = models.DateTimeField
	albumLastAccessedTime = models.DateTimeField

	def __str__(self):
		return ' Name of Album ' + str(self.pk) + ' ' + self.albumName

class Photo(models.Model):
	album = models.ForeignKey(Album,on_delete=models.CASCADE)
	photoName = models.CharField(max_length=20)
	photoDescription = models.CharField(max_length=1024)
	photoPath = models.FileField(null=False,blank=False)
	photoSizeInMB = models.IntegerField
	photoCreatedTime = models.DateTimeField(auto_now_add=True, blank=True)
	photoModifiedTime = models.DateTimeField(auto_now=True)
	photoLastAccessedTime = models.DateTimeField(auto_now_add=True, blank=True)

	def __str__(self):
		return self.album.albumName + ':' + self.photoName  