# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(max_length=20)),
                ('photoDescription', models.CharField(max_length=1024)),
                ('photoPath', models.CharField(max_length=512)),
            ],
        ),
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='albumName',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album'),
        ),
    ]
