# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170212_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photoCreatedTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 12, 18, 10, 52, 80748, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photoLastAccessedTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 12, 18, 11, 7, 470560, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photoModifiedTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 12, 18, 11, 17, 133251, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
