# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170212_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoModifiedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
