# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170212_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoPath',
            field=models.FileField(upload_to=''),
        ),
    ]
